[Fix] Allow addition of non-xml parsers
Parsing non-xml format like JSON would finish with strange exception (see below), instead of notifying user that parsing is not supported:
```
Unexpected error while parsing file: Unable to resolve whether file was generated by Enterprise Architect
com.akaene.stpa.scs.exception.ControlStructureParserException: Unable to resolve whether file was generated by Enterprise Architect
	at com.akaene.stpa.scs.parser.sysml.EnterpriseArchitectSysMLXMIParser.isEnterpriseArchitectFile(EnterpriseArchitectSysMLXMIParser.java:126)
```